name: Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 22
        stylelint-version:
          - 16
    runs-on: ${{ matrix.system }}
    name: Stylelint v${{ matrix.stylelint-version }} | ${{ matrix.system }} | node v${{ matrix.node-version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Use Node LTS version
        uses: actions/setup-node@v5
        with:
          cache: yarn
          node-version: ${{ matrix.node-version}}

      - name: Enable Corepack
        run: corepack enable

      ## --- YARN CACHE --- ##
      - name: Check for cached dependencies
        continue-on-error: true
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            .cache/yarn
            node_modules
          key: ${{ matrix.system }}-node${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Set stylelint version
        run: yarn add -D stylelint@^${{ matrix.stylelint-version }}

      - name: Run test suite
        run: yarn test --ci --reporters github-actions

  coverage:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Coverage reporting
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Use Node LTS version
        uses: actions/setup-node@v5
        with:
          cache: yarn
          node-version: 22

      ## --- YARN CACHE --- ##
      - name: Check for cached dependencies
        continue-on-error: true
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            .cache/yarn
            node_modules
          key: ubuntu-latest-node22-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run coverage report
        run: yarn coverage --ci

      - name: Coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          format: "markdown"
          output: "both"
          fail_below_min: "true"
          thresholds: "80 100"

      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2.9.4
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to job summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
